# Generated by Django 3.2 on 2023-01-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Is_generated',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_generated', models.BooleanField(default=False)),
            ],
        ),
    ]
