# Generated by Django 3.2 on 2023-01-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_is_generated_is_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track_fee',
            name='date_transaction',
            field=models.DateTimeField(max_length=45),
        ),
    ]
