# Generated by Django 3.2 on 2023-01-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_track_fee_date_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track_fee',
            name='date_transaction',
            field=models.DateTimeField(),
        ),
    ]
